import type { Metadata } from "next";
import "./globals.css";
import ReactQueryProvider from "./config/ReactQueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body>
          <p>from layout</p>
          {children}
        </body>
      </html>
    </ReactQueryProvider>
  );
}
